SELECT * FROM customer
-- 1. Revenue generated by gender
SELECT gender, SUM(purchase_amount) AS total_revenue FROM customer
GROUP BY gender ORDER BY total_revenue DESC

-- 2. Customers who used discount still 
--spent more than average purchase amount
SELECT customer_id, purchase_amount FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)

-- 3. top 5 products with highest avg. review rating
SELECT item_purchased, 
ROUND(AVG(review_rating)::numeric, 2) as avg_rating 
FROM customer
GROUP BY item_purchased 
ORDER BY avg_rating DESC LIMIT 5

--4. compare avg. purchase amount b/w standard and express delivery
SELECT shipping_type, ROUND(AVG(purchase_amount)::numeric,2) AS avg_spend
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type

-- 5. subscribers spend more or unsubscribers??avg.spend n total revenue
SELECT subscription_status, 
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC

-- 6. which products rely heavily on discounts?
-- 5 products with high percentage of purchase with discount applied
SELECT item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) 
AS discount_percentage FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC LIMIT 5

-- 7. segment customers into new, returning, & loyal based on their total number of previous purchases
-- count of each segment
WITH customer_types AS(
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "number of customers"
FROM customer_types
GROUP BY customer_segment

-- 8. top 3 most purchased product within each category
WITH product_counts AS(
SELECT category, item_purchased, 
COUNT(customer_id) AS purchase_count,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS product_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT product_rank, category, item_purchased, purchase_count 
FROM product_counts WHERE product_rank <=3;

-- 9. customer who are repeat buyers(mor than 5 purchases) are suscribers??
SELECT subscription_status, 
count(customer_id) AS repeat_buyers 
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers

-- 10. revenue by age group
SELECT age_group, SUM(purchase_amount) AS total_revenue FROM customer
GROUP BY age_group ORDER BY total_revenue DESC